version: "3"
services:
  mysql:
    container_name: mysql 
    image: mysql:latest
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - ./data/mysql:/data/mysql
    env_file:
    - dev.env
    networks:
    - db

  adminer:
    links:
    - mysql:mysql
    container_name: adminer
    image: adminer
    restart: always
    ports:
    - "8080:8080"
    volumes:
    - ./data/adminer:/root/.adminer
    env_file:
    - dev.env
    networks:
    - db

networks:
  postgres:
    driver: bridge